services:
  db:
    image: mysql

    environment:
      MYSQL_DATABASE: ${NAME}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
    - ./data/mysql/db:/var/lib/mysql

  backend:
    build: .
    ports:
      - "8200:8200"
    depends_on:
      - db
    container_name: ghosted_app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8200"

